# Generated by Django 5.1.7 on 2025-08-22 22:59

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Teléfono')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula')),
                ('oficio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Oficio')),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('administrador', 'Administrador')], default='usuario', max_length=20, verbose_name='Rol')),
                ('foto_perfil', models.ImageField(blank=True, default='photo_profiles/default_avatar.png', null=True, upload_to='photo_profiles/', verbose_name='Foto de Perfil')),
                ('groups', models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece este usuario.', related_name='custom_user_groups_set', related_query_name='custom_user_group', to='auth.group', verbose_name='Grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='custom_user_permissions_set', related_query_name='custom_user_permission', to='auth.permission', verbose_name='Permisos de Usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del Objeto')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('activo', models.BooleanField(default=True, verbose_name='Comentario Activo')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Contenido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Código de Factura')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del Objeto')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Total')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Pagado')),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado del Pago')),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Método de Pago')),
                ('comprobante_pago', models.ImageField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante de Pago')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Contenido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del Objeto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='contenido_images/', verbose_name='Imagen')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activa', models.BooleanField(default=True, verbose_name='Imagen Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Contenido')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Código de Orden')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del Objeto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal')),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Contenido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Código de Pago')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del Objeto')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('otro', 'Otro')], default='efectivo', max_length=20, verbose_name='Método de Pago')),
                ('comprobante_pago', models.ImageField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante de Pago')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Contenido')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='sanes.factura', verbose_name='Factura')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='sanes.orden', verbose_name='Orden')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título de la Rifa')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('premio', models.CharField(blank=True, max_length=200, verbose_name='Premio')),
                ('precio_ticket', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio por Ticket')),
                ('total_tickets', models.PositiveIntegerField(default=100, verbose_name='Total de Tickets')),
                ('tickets_disponibles', models.PositiveIntegerField(default=100, verbose_name='Tickets Disponibles')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Cierre')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='rifas_images/', verbose_name='Imagen de la Rifa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rifas_ganadas', to=settings.AUTH_USER_MODEL, verbose_name='Ganador')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rifas_organizadas', to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
            ],
            options={
                'verbose_name': 'Rifa',
                'verbose_name_plural': 'Rifas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='San',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre del San')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Total')),
                ('numero_cuotas', models.PositiveIntegerField(default=1, verbose_name='Número de Cuotas')),
                ('precio_cuota', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio por Cuota')),
                ('total_participantes', models.PositiveIntegerField(default=10, verbose_name='Total de Participantes')),
                ('participantes_actuales', models.PositiveIntegerField(default=0, verbose_name='Participantes Actuales')),
                ('frecuencia_pago', models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], default='mensual', max_length=20, verbose_name='Frecuencia de Pago')),
                ('tipo', models.CharField(choices=[('ahorro', 'Ahorro'), ('producto', 'Producto'), ('servicio', 'Servicio')], default='ahorro', max_length=20, verbose_name='Tipo de San')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(default=datetime.date.today, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(default=datetime.date.today, verbose_name='Fecha de Finalización')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='sanes_images/', verbose_name='Imagen del San')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanes_organizados', to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
            ],
            options={
                'verbose_name': 'San',
                'verbose_name_plural': 'Sanes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipacionSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('orden_cobro', models.PositiveIntegerField(default=1, verbose_name='Orden de Cobro')),
                ('activa', models.BooleanField(default=True, verbose_name='Participación Activa')),
                ('cuotas_pagadas', models.PositiveIntegerField(default=0, verbose_name='Cuotas Pagadas')),
                ('fecha_ultima_cuota', models.DateField(blank=True, null=True, verbose_name='Fecha de Última Cuota')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_san', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('san', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='sanes.san', verbose_name='San')),
            ],
            options={
                'verbose_name': 'Participación en San',
                'verbose_name_plural': 'Participaciones en San',
                'ordering': ['orden_cobro'],
                'unique_together': {('san', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='Cupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_semana', models.PositiveIntegerField(default=1, verbose_name='Número de Semana')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='disponible', max_length=20, verbose_name='Estado')),
                ('asignado', models.BooleanField(default=False, verbose_name='Cupo Asignado')),
                ('monto_cuota', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto de la Cuota')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupos', to='sanes.factura', verbose_name='Factura')),
                ('participacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupos', to='sanes.participacionsan', verbose_name='Participación')),
                ('san', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupos', to='sanes.san', verbose_name='San')),
            ],
            options={
                'verbose_name': 'Cupo',
                'verbose_name_plural': 'Cupos',
                'ordering': ['numero_semana'],
                'unique_together': {('san', 'numero_semana')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Código del Ticket')),
                ('numero', models.PositiveIntegerField(default=1, verbose_name='Número de Ticket')),
                ('fecha_compra', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Compra')),
                ('precio_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Pagado')),
                ('activo', models.BooleanField(default=True, verbose_name='Ticket Activo')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='sanes.factura', verbose_name='Factura')),
                ('rifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='sanes.rifa', verbose_name='Rifa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_comprados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['numero'],
                'unique_together': {('rifa', 'numero')},
            },
        ),
    ]
