# Generated by Django 5.1.7 on 2025-08-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='photo_profiles/default_avatar.png', null=True, upload_to='photo_profiles/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='oficio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
