# Generated by Django 5.1.7 on 2025-08-27 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rifa', 'Rifa'), ('san', 'San'), ('usuario', 'Usuario'), ('finanzas', 'Finanzas')], max_length=20)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='SorteoRifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sorteo', models.DateTimeField(auto_now_add=True)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='rifas/evidencias/')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorteos', to='sanes.rifa')),
                ('ticket_ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorteos_ganados', to='sanes.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_turno', models.PositiveIntegerField()),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('cumplido', models.BooleanField(default=False)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='sanes.participacionsan')),
                ('san', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='sanes.san')),
            ],
            options={
                'ordering': ['numero_turno'],
                'unique_together': {('san', 'numero_turno')},
            },
        ),
    ]
