# Generated by Django 5.1.7 on 2025-08-08 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanes', '0002_customuser_cedula_customuser_foto_perfil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tickets', models.PositiveIntegerField(help_text='Total de tickets disponibles para la rifa')),
                ('image', models.ImageField(upload_to='raffle_products/')),
                ('draw_date', models.DateField(help_text='Fecha en que se realizará el sorteo')),
                ('is_active', models.BooleanField(default=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffles_organized', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RaffleTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('ticket_number', models.CharField(max_length=50)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='sanes.raffle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
