# Generated by Django 5.1.7 on 2025-08-27 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sanes', '0002_historialaccion_mensaje_notificacion_reporte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del Objeto')),
                ('texto', models.TextField(verbose_name='Comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Contenido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('pagar', 'Pagar'), ('confirmar', 'Confirmar'), ('rechazar', 'Rechazar'), ('comentar', 'Comentar'), ('unirse', 'Unirse'), ('salir', 'Salir'), ('login', 'Iniciar Sesión'), ('logout', 'Cerrar Sesión'), ('registro', 'Registro'), ('admin', 'Acción Administrativa')], max_length=20, verbose_name='Tipo de Acción')),
                ('nivel', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('success', 'Éxito')], default='info', max_length=10, verbose_name='Nivel')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del Objeto')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('datos_adicionales', models.JSONField(blank=True, default=dict, verbose_name='Datos Adicionales')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Contenido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log del Sistema',
                'verbose_name_plural': 'Logs del Sistema',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'tipo_accion'], name='sanes_syste_usuario_ae6661_idx'), models.Index(fields=['fecha_creacion'], name='sanes_syste_fecha_c_f2a41b_idx'), models.Index(fields=['nivel'], name='sanes_syste_nivel_d86b87_idx')],
            },
        ),
    ]
