# Generated by Django 5.1.7 on 2025-08-08 07:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanes', '0003_raffle_raffleticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raffle',
            options={'verbose_name': 'Rifa', 'verbose_name_plural': 'Rifas'},
        ),
        migrations.RemoveField(
            model_name='raffle',
            name='image',
        ),
        migrations.RemoveField(
            model_name='raffle',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='raffle',
            name='organizer',
        ),
        migrations.AddField(
            model_name='raffle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='san',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='san',
            name='description',
            field=models.TextField(default='Descripción no disponible'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='san',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='san',
            name='total_boletos',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='description',
            field=models.TextField(default='Descripción no disponible', verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='raffle',
            name='draw_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Sorteo'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del Ticket'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título de la Rifa'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='total_tickets',
            field=models.IntegerField(verbose_name='Tickets Totales'),
        ),
        migrations.AlterField(
            model_name='san',
            name='cuota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='san',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sanes_images/'),
        ),
        migrations.AlterField(
            model_name='san',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanes.raffle', verbose_name='Rifa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='raffle_images/', verbose_name='Archivo de Imagen')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sanes.raffle', verbose_name='Rifa')),
            ],
        ),
    ]
