# Generated by Django 5.1.7 on 2025-09-02 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanes', '0003_comment_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='facturas/', verbose_name='Archivo'),
        ),
        migrations.AddField(
            model_name='factura',
            name='concepto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='factura',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AddField(
            model_name='factura',
            name='rifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sanes.rifa', verbose_name='Rifa'),
        ),
        migrations.AddField(
            model_name='factura',
            name='san',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sanes.san', verbose_name='San'),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo',
            field=models.CharField(choices=[('rifa', 'Rifa'), ('san', 'San'), ('cuota_san', 'Cuota de San'), ('ticket_rifa', 'Ticket de Rifa'), ('inscripcion_san', 'Inscripción a San'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo'),
        ),
    ]
