# Generated by Django 5.1.7 on 2025-08-08 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanes', '0004_alter_raffle_options_remove_raffle_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='san',
            name='fecha_fin',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Cierre'),
        ),
    ]
