# Generated by Django 5.1.7 on 2025-09-02 10:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sanes', '0004_factura_archivo_factura_concepto_factura_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='usuario',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado Hasta'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='documento_identidad',
            field=models.FileField(blank=True, null=True, upload_to='documentos_identidad/', verbose_name='Documento de Identidad'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dos_fa_habilitado',
            field=models.BooleanField(default=False, verbose_name='2FA Habilitado'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_verificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificación'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='intentos_login_fallidos',
            field=models.PositiveIntegerField(default=0, verbose_name='Intentos de Login Fallidos'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nivel_reputacion',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('confiable', 'Confiable'), ('excelente', 'Excelente'), ('premium', 'Premium')], default='nuevo', max_length=20, verbose_name='Nivel de Reputación'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='puntuacion_reputacion',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Puntuación de Reputación'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ultimo_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Login'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verificado',
            field=models.BooleanField(default=False, verbose_name='Usuario Verificado'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario Participante'), ('organizador', 'Organizador'), ('administrador', 'Administrador del Sistema')], default='usuario', max_length=20, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='NotificacionMejorada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pago', 'Pago'), ('rifa', 'Rifa'), ('san', 'San'), ('sistema', 'Sistema'), ('admin', 'Administrativa'), ('recordatorio', 'Recordatorio')], max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('canal', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('push', 'Notificación Push'), ('interno', 'Interno')], default='interno', max_length=20, verbose_name='Canal')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20, verbose_name='Prioridad')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('enviado', models.BooleanField(default=False, verbose_name='Enviado')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_mejoradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación Mejorada',
                'verbose_name_plural': 'Notificaciones Mejoradas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PagoSimulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_transaccion', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Código de Transacción')),
                ('metodo_pago', models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('nequi', 'Nequi'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria')], max_length=20, verbose_name='Método de Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('moneda', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Procesamiento'), ('procesando', 'Procesando'), ('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia Externa')),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('tiempo_procesamiento', models.PositiveIntegerField(default=0, verbose_name='Tiempo de Procesamiento (segundos)')),
                ('intentos', models.PositiveIntegerField(default=1, verbose_name='Número de Intentos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_simulados', to='sanes.factura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_simulados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago Simulado',
                'verbose_name_plural': 'Pagos Simulados',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.AddIndex(
            model_name='notificacionmejorada',
            index=models.Index(fields=['usuario', 'leido'], name='sanes_notif_usuario_e52a78_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacionmejorada',
            index=models.Index(fields=['tipo', 'canal'], name='sanes_notif_tipo_1df145_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacionmejorada',
            index=models.Index(fields=['prioridad'], name='sanes_notif_priorid_1ad3e9_idx'),
        ),
    ]
