# Generated by Django 5.1.7 on 2025-09-02 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sanes', '0005_remove_imagen_content_type_remove_orden_content_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turnosan',
            options={'ordering': ['numero_turno'], 'verbose_name': 'Turno de San', 'verbose_name_plural': 'Turnos de San'},
        ),
        migrations.AddField(
            model_name='comment',
            name='comentario_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='sanes.comment', verbose_name='Comentario Padre'),
        ),
        migrations.AddField(
            model_name='comment',
            name='editado',
            field=models.BooleanField(default=False, verbose_name='Editado'),
        ),
        migrations.AddField(
            model_name='comment',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('moderado', 'Moderado'), ('eliminado', 'Eliminado'), ('oculto', 'Oculto')], default='activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='comment',
            name='fecha_edicion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Edición'),
        ),
        migrations.AddField(
            model_name='comment',
            name='fecha_moderacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Moderación'),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_moderados', to=settings.AUTH_USER_MODEL, verbose_name='Moderado Por'),
        ),
        migrations.AddField(
            model_name='comment',
            name='motivo_moderacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Moderación'),
        ),
        migrations.AddField(
            model_name='comment',
            name='texto_original',
            field=models.TextField(blank=True, null=True, verbose_name='Texto Original'),
        ),
        migrations.AddField(
            model_name='comment',
            name='votos_negativos',
            field=models.PositiveIntegerField(default=0, verbose_name='Votos Negativos'),
        ),
        migrations.AddField(
            model_name='comment',
            name='votos_positivos',
            field=models.PositiveIntegerField(default=0, verbose_name='Votos Positivos'),
        ),
        migrations.AddField(
            model_name='turnosan',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('cumplido', 'Cumplido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado del Turno'),
        ),
        migrations.AddField(
            model_name='turnosan',
            name='fecha_cumplimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cumplimiento'),
        ),
        migrations.AddField(
            model_name='turnosan',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AddField(
            model_name='turnosan',
            name='monto_turno',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto del Turno'),
        ),
        migrations.AddField(
            model_name='turnosan',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas del Turno'),
        ),
        migrations.AddField(
            model_name='turnosan',
            name='pagos_previos_validados',
            field=models.BooleanField(default=False, verbose_name='Pagos Previos Validados'),
        ),
        migrations.AlterField(
            model_name='turnosan',
            name='cumplido',
            field=models.BooleanField(default=False, verbose_name='Cumplido'),
        ),
        migrations.AlterField(
            model_name='turnosan',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación'),
        ),
        migrations.AlterField(
            model_name='turnosan',
            name='numero_turno',
            field=models.PositiveIntegerField(verbose_name='Número de Turno'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'object_id'], name='sanes_comme_content_de5eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['usuario', 'estado'], name='sanes_comme_usuario_5f25a2_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['fecha_creacion'], name='sanes_comme_fecha_c_a55d45_idx'),
        ),
    ]
