# Generated by Django 5.1.7 on 2025-08-08 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanes', '0005_alter_san_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='raffle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sanes.raffle'),
        ),
        migrations.AlterField(
            model_name='order',
            name='san',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sanes.san'),
        ),
    ]
