# Generated by Django 5.1.7 on 2025-08-08 09:38

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanes', '0006_order_raffle_alter_order_san'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raffle',
            options={},
        ),
        migrations.RemoveField(
            model_name='raffle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='raffle',
            name='draw_date',
        ),
        migrations.RemoveField(
            model_name='raffle',
            name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='raffle',
            name='total_tickets',
        ),
        migrations.AddField(
            model_name='raffle',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2025, 8, 8)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raffle',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raffle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='raffle_images/'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='num_cuotas',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raffle',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organized_raffles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raffle',
            name='prize_name',
            field=models.CharField(default='Premio por defecto', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raffle',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='raffle',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='raffle',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
