# Generated by Django 5.1.7 on 2025-08-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanes', '0007_alter_raffle_options_remove_raffle_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raffle',
            name='title',
        ),
    ]
