# Generated by Django 5.1.7 on 2025-08-08 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanes', '0010_raffle_ganador_factura_participantesan_aporte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('san', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='sanes.san')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
