# Generated by Django 5.1.7 on 2025-08-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanes', '0011_ticketsan'),
    ]

    operations = [
        migrations.AddField(
            model_name='san',
            name='total_participantes_actuales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='san',
            name='total_participantes',
            field=models.IntegerField(),
        ),
    ]
