# Generated by Django 5.1.7 on 2025-08-08 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanes', '0012_san_total_participantes_actuales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsan',
            name='numero',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketsan',
            name='codigo_unico',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketsan',
            name='san',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanes.san'),
        ),
    ]
